site_name: "SANS SEC510 Cloud Security Flight Simulator Instructions"
copyright: "©2024 Brandon Evans and Eric Johnson"
site_description: "SANS SEC510 Cloud Security Flight Simulator setup instructions and bootstrap template."
site_author: "Brandon Evans and Eric Johnson"

theme:
  name: "material"
  palette:
    primary: "orange"
    accent: "deep orange"
  # option 1: internal icons
  icon:
    logo: "material/cloud-lock-outline"

  # use https://favicon.io/favicon-converter/ for this
  favicon: "img/favicon.ico"
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - content.code.annotate
    - content.code.copy

nav:
  - Home: "index.md"
  - Versions:
      - J01: "j01.md"

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: false
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
